services:
  db:
    image: postgres:15-alpine
    container_name: fridge-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fridge_db
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: fridge-backend
    ports:
      - "8081:8080" # Снаружи 8081, внутри контейнера 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fridge_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: fridge-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
