spring:
  datasource:
    url: jdbc:postgresql://db:5432/cookie
    username: cookie
    password: cookie
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
